### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by matcha6666** [0xUndetectable/pornhub_scraper#1]
File "C:\Users\windows\Desktop\pornhub_scraper-main\run.py", line 6, in <module>
    from util.m3u8 import download
  File "C:\Users\windows\Desktop\pornhub_scraper-main\util\m3u8.py", line 8, in <module>
    from random_user_agent.user_agent import UserAgent
ModuleNotFoundError: No module named 'random_user_agent'

**Comment by 0xUndetectable** [comment]
pip install random-user-agent
follow yt tutorial

**Comment by matcha6666** [comment]
> 点安装随机用户代理遵循 YT 教程

But，A 10054 connection error occurred
 ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by 0xUndetectable** [comment]
Line of the code ?

**Comment by matcha6666** [comment]
> 代码行 ？

C:\Users\windows\Desktop\pornhub_scraper-main>    python run.py
INSERT URL => https://it.pornhub.com/view_video.php?viewkey=64c9ad5d92a58#1
Traceback (most recent call last):
  File "E:\python\anaconda\Lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "E:\python\anaconda\Lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "E:\python\anaconda\Lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "E:\python\anaconda\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\python\anaconda\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "E:\python\anaconda\Lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "E:\python\anaconda\Lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "E:\python\anaconda\Lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "E:\python\anaconda\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接 。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\windows\Desktop\pornhub_scraper-main\run.py", line 35, in <module>
    main_download(url)
  File "C:\Users\windows\Desktop\pornhub_scraper-main\run.py", line 9, in main_download
    r = requests.get(url)
        ^^^^^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\anaconda\Lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by 0xUndetectable** [comment]
Try outside anaconda

**Comment by matcha6666** [comment]
> 尝试在蟒蛇外面

C:\Users\windows\Desktop\pornhub_scraper-main>    python run.py
INSERT URL => https://cn.pornhub.com/view_video.php?viewkey=64e969d3a0f37
Traceback (most recent call last):
  File "E:\Python\Python311\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "E:\Python\Python311\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "E:\Python\Python311\Lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "E:\Python\Python311\Lib\site-packages\urllib3\connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000115E03F5890>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "E:\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "E:\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cn.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=64e969d3a0f37 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000115E03F5890>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\windows\Desktop\pornhub_scraper-main\run.py", line 35, in <module>
    main_download(url)
  File "C:\Users\windows\Desktop\pornhub_scraper-main\run.py", line 9, in main_download
    r = requests.get(url)
        ^^^^^^^^^^^^^^^^^
  File "E:\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\Python311\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cn.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=64e969d3a0f37 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000115E03F5890>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))


I uninstall anaconda, uninstall and reinstall pycharm, rerun，you say Try outside anaconda, do not use anaconda's interpreter?

**Comment by 0xUndetectable** [comment]
In my setup i use python 3.9 and all requirement, try with this i didn't test with anaconda but i think is a package conflict

**Comment by 0xUndetectable** [comment]
Try simple request to the url if it show error with only request is a problem with setup

**Comment by matcha6666** [comment]
> 尝试对 url 的简单请求，如果它显示错误，只有请求是设置问题
I requested the url and got a connection error

import requests

url = 'https://cn.pornhub.com/view_video.php?viewkey=64e969d3a0f37'

headers = {'User-Agent':
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.69'}

response = requests.get(url=url, headers=headers)

print(response)



"E:\Python\PyCharm Community Edition\pythonProject\venv\Scripts\python.exe" "E:\Python\PyCharm Community Edition\pythonProject\main.py" 
Traceback (most recent call last):
  File "E:\Python\PyCharm Community Edition\pythonProject\venv\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\PyCharm Community Edition\pythonProject\venv\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "E:\Python\PyCharm Community Edition\pythonProject\venv\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Python\PyCharm Community Edition\pythonProject\venv\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "E:\Python\PyCharm Community Edition\pythonProject\venv\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Python\PyCharm Community Edition\pythonProject\venv\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Python\PyCharm Community Edition\pythonProject\venv\Lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "E:\Python\PyCharm Community Edition\pythonProject\venv\Lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "E:\Python\PyCharm Community Edition\pythonProject\venv\Lib\site-packages\urllib3\connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000240A576EC50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Python\PyCharm Community Edition\pythonProject\venv\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "E:\Python\PyCharm Community Edition\pythonProject\venv\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "E:\Python\PyCharm Community Edition\pythonProject\venv\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cn.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=64e969d3a0f37 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000240A576EC50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python\PyCharm Community Edition\pythonProject\main.py", line 8, in <module>
    response = requests.get(url=url, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\PyCharm Community Edition\pythonProject\venv\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\PyCharm Community Edition\pythonProject\venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\PyCharm Community Edition\pythonProject\venv\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\PyCharm Community Edition\pythonProject\venv\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Python\PyCharm Community Edition\pythonProject\venv\Lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cn.pornhub.com', port=443): Max retries exceeded with url: /view_video.php?viewkey=64e969d3a0f37 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000240A576EC50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

Process finished with exit code 1

**Comment by 0xUndetectable** [comment]
USING:

"""import requests
url = 'https://cn.pornhub.com/view_video.php?viewkey=64e969d3a0f37'
headers = {'User-Agent':
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.69'}
response = requests.get(url=url, headers=headers)
print(response)"""

for me work perfecetly. Try to disinstall pycharm, anaconda and all python, reinstall python from this -> https://www.python.org/downloads/release/python-390/ and the stuff in the video, and try the same code.

**Comment by 0xUndetectable** [comment]
this i think is your video -> https://www.mediafire.com/file/wzt3z1lzme2f6qk/4k_エロフェラ.mp4/file

**Comment by matcha6666** [comment]
> 我认为这是你的视频 -> [https://www.mediafire.com/file/wzt3z1lzme2f6qk/4k_エロフェラ.mp4/文件](https://www.mediafire.com/file/wzt3z1lzme2f6qk/4k_%E3%82%A8%E3%83%AD%E3%83%95%E3%82%A7%E3%83%A9.mp4/file)

Yes, I'm going to try again the way you said

**Comment by 0xUndetectable** [comment]
ok

**Comment by matcha6666** [comment]
> ok

When I reinstall python3.9, the connection error will still occur when I re-run the code, and the simple request url will also result in the connection error. If others can run normally, it is the problem of my computer itself, so I will not worry about this connection error. When I have time to reinstall windows system, I will try again

**Comment by matcha6666** [comment]
> 还行
I re-installed python3.9, re-running the code will still be connected to the error, simple request url will also be connected to the error, others can run normally, that is the problem of my computer itself, wait for free to reinstall windows system, try again

**Comment by matcha6666** [comment]
> 还行


When I reinstall python3.9, I still get a connection error when I re-run the code, and I also get a connection error when I simply request the url. If someone else can run it properly, that's the problem with my computer. I'll try again when I have time to reinstall windows

**Comment by 0xUndetectable** [comment]
ok, yeah i think is a problem with win
