### ISSUE TITLE
Error when downloading video

### ISSUE THREAD

**Issue by greyhat94** [0xUndetectable/pornhub_scraper#2]
Hi! I was trying to use your script, and I came across to an error after providing with the video URL. This is the output I've got: 

```
SyntaxError: Unexpected token ','
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.18.0
Traceback (most recent call last):
  File "C:\Users\umile\Desktop\Pornhub Scraper\run.py", line 35, in <module>
    main_download(url)
  File "C:\Users\umile\Desktop\Pornhub Scraper\run.py", line 22, in main_download
    output = subprocess.check_output(['node', 'index.js'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\umile\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['node', 'index.js']' returned non-zero exit status 1".

```

Could you help me to fix this? Your help will be much appreciated.

**Comment by 0xUndetectable** [comment]
Retry now

**Comment by greyhat94** [comment]
> Retry now

Thank you for updating your script. Now, everything seems to be working. I'll update you if anything. You're great.
